name: 'Next Version'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GIT_AUTHOR_NAME: 'CI Bot'
  GIT_AUTHOR_EMAIL: ci-bot@roller.de
  GIT_COMMITTER_NAME: 'CI Bot'
  GIT_COMMITTER_EMAIL: ci-bot@roller.de
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

on:
  push:
    branches:
      - main
      - beta

jobs:
  next-version:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    strategy:
      matrix:
        node-version: [ 24.13.0 ]

    steps:
      - name: 'Check out Git repository'
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Install pnpm
        uses: pnpm/action-setup@a15d269cd4658e1107c09f1fabf4cbd7bd1f308a # v4.4.0

      - name: Set node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'

      - name: 'Install Node.js dependencies'
        run: pnpm install --frozen-lockfile

      - name: 'Starting semantic release'
        run: pnpm exec semantic-release
