name: 'Next Version'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GIT_AUTHOR_NAME: 'CI Bot'
  GIT_AUTHOR_EMAIL: ci-bot@roller.de
  GIT_COMMITTER_NAME: 'CI Bot'
  GIT_COMMITTER_EMAIL: ci-bot@roller.de
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

on:
  push:
    branches:
      - main
      - beta

jobs:
  next-version:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 20.14.0 ]

    steps:
      - name: 'Check out Git repository'
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node
        uses: actions/setup-node@v3
        # TODO
        # with:
        #   node-version: ${{ matrix.node-version }}
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Setup ni
        run: npm i -g @antfu/ni

      - name: 'Install Node.js dependencies'
        # run: npm ci
        run: nci

      - name: 'Starting semantic release'
        run: npx semantic-release
        # run: nlx semantic-release
