name: 'Next Version'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GIT_AUTHOR_NAME: EinfachHans
  GIT_AUTHOR_EMAIL: hanskrywaa@web.de
  GIT_COMMITTER_NAME: EinfachHans
  GIT_COMMITTER_EMAIL: hanskrywaa@web.de
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

on:
  push:
    branches:
      - main
      - beta

jobs:
  next-version:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.16.0 ]

    steps:
      - name: 'Check out Git repository'
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Setup ni
        run: npm i -g @antfu/ni

      - name: Install
        run: nci

      - name: 'Starting semantic release'
        run: nr semantic-release
