name: 'Run Verify'

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches-ignore:
      - 'beta'
      - 'main'

jobs:
  run-verify:
    name: 'Run Verify'
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [ 18.16.0 ]

    steps:
      - name: 'Check out Git repository'
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Setup ni
        run: npm i -g @antfu/ni

      - name: Install
        run: nci

      - name: 'Run Verify'
        run: nr verify
